# Generated by Django 6.1 on 2026-08-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit_card', 'Tarjeta de crédito'), ('debit_card', 'Tarjeta de débito'), ('bank', 'Cuenta bancaria'), ('nequi', 'Nequi'), ('other', 'Otro')], max_length=50)),
                ('last_four', models.CharField(blank=True, max_length=4, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=7, null=True)),
                ('holder_name', models.CharField(max_length=150)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
