# Generated by Django 6.1 on 2026-08-23 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('estimated_processing_date', models.DateField(blank=True, null=True)),
                ('processing_date', models.DateField(blank=True, null=True)),
                ('initial_birds', models.IntegerField()),
                ('current_birds', models.IntegerField()),
                ('mortality', models.IntegerField(default=0)),
                ('initial_average_weight', models.FloatField()),
                ('current_average_weight', models.FloatField()),
                ('feed_consumption', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('in_breeding', 'En crianza'), ('ready_for_processing', 'Listo para procesamiento'), ('processed', 'Procesado'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado')], default='planned', max_length=30)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_date', models.DateField()),
                ('processed_birds', models.IntegerField()),
                ('live_weight_total', models.FloatField()),
                ('processed_weight', models.FloatField()),
                ('average_weight', models.FloatField()),
                ('waste', models.FloatField()),
                ('waste_percentage', models.FloatField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processings', to='production.productionbatch')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('birds_count', models.IntegerField()),
                ('average_weight', models.FloatField()),
                ('feed_consumption', models.FloatField()),
                ('mortality', models.IntegerField(default=0)),
                ('observations', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='production.productionbatch')),
            ],
        ),
    ]
